"""empty message

Revision ID: 1755a31c868c
Revises: af72ec06cf06
Create Date: 2025-08-09 20:00:15.952849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1755a31c868c'
down_revision: Union[str, Sequence[str], None] = 'af72ec06cf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('following')
        batch_op.drop_column('follower')

    # ### end Alembic commands ###
