"""empty message

Revision ID: 20d38f87e3ad
Revises: 4eeeaf36d9ba
Create Date: 2025-08-06 15:59:48.902755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d38f87e3ad'
down_revision: Union[str, Sequence[str], None] = '4eeeaf36d9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_nickname'), 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_nickname'), 'user', type_='unique')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
