"""empty message

Revision ID: 2e2a8708dcb2
Revises: 927cbdddf1de
Create Date: 2025-07-30 15:10:22.396713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2a8708dcb2'
down_revision: Union[str, Sequence[str], None] = '927cbdddf1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name=op.f('fk_review_voter_review_id_review')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_review_voter_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'review_id', name=op.f('pk_review_voter'))
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_review_paper_id_papers'), 'papers', ['paper_id'], ['arxiv_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_paper_id_papers'), type_='foreignkey')

    op.drop_table('review_voter')
    # ### end Alembic commands ###
