"""empty message

Revision ID: 37fb65d0e141
Revises: 
Create Date: 2025-08-09 14:01:38.543717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fb65d0e141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_likes_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_paper_likes_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_likes')),
    sa.UniqueConstraint('user_id', 'paper_id', name='unique_user_paper_like')
    )
    with op.batch_alter_table('paper_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_likes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_likes_id'))

    op.drop_table('paper_likes')
    # ### end Alembic commands ###
