"""empty message

Revision ID: 4111300faa3a
Revises: e1c0891681f4
Create Date: 2025-07-31 14:33:11.346739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4111300faa3a'
down_revision: Union[str, Sequence[str], None] = 'e1c0891681f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.id'], name=op.f('fk_folders_parent_folder_id_folders')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_folders_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_id'))

    op.drop_table('folders')
    # ### end Alembic commands ###
