"""Init

Revision ID: 4f424f6f8541
Revises: 4dcf0f361a0d
Create Date: 2025-08-01 15:59:08.634170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f424f6f8541'
down_revision: Union[str, Sequence[str], None] = '4dcf0f361a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_read_papers_paper_id'), table_name='read_papers')
    op.drop_index(op.f('ix_read_papers_user_id'), table_name='read_papers')
    op.drop_table('read_papers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_papers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('paper_id', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_read_papers_paper_id_papers')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_read_papers_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_papers')),
    sa.UniqueConstraint('user_id', 'paper_id', name=op.f('uq_user_paper'))
    )
    op.create_index(op.f('ix_read_papers_user_id'), 'read_papers', ['user_id'], unique=False)
    op.create_index(op.f('ix_read_papers_paper_id'), 'read_papers', ['paper_id'], unique=False)
    # ### end Alembic commands ###
