"""empty message

Revision ID: 8df43d3c8e6d
Revises: 00005bb1a867
Create Date: 2025-08-12 11:11:44.186913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df43d3c8e6d'
down_revision: Union[str, Sequence[str], None] = '00005bb1a867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_paper_id_papers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_paper_id_papers'), 'papers', ['paper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_paper_id_papers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_paper_id_papers'), 'papers', ['paper_id'], ['arxiv_id'])

    # ### end Alembic commands ###
