"""empty message

Revision ID: 927cbdddf1de
Revises: 8679439c1d74
Create Date: 2025-07-29 21:04:02.920121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927cbdddf1de'
down_revision: Union[str, Sequence[str], None] = '8679439c1d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'review', 'papers', ['paper_id'], ['arxiv_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    # ### end Alembic commands ###
