"""empty message

Revision ID: db15c0bfcfba
Revises: 20d38f87e3ad
Create Date: 2025-08-06 16:02:06.360573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db15c0bfcfba'
down_revision: Union[str, Sequence[str], None] = '20d38f87e3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_nickname'), 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_nickname'), 'user', type_='unique')
    # ### end Alembic commands ###
