"""empty message

Revision ID: e1c0891681f4
Revises: 2e2a8708dcb2
Create Date: 2025-07-31 14:27:03.459998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c0891681f4'
down_revision: Union[str, Sequence[str], None] = '2e2a8708dcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_read_papers_paper_id_papers')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_read_papers_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_papers')),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_user_paper')
    )
    with op.batch_alter_table('read_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_read_papers_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_read_papers_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('read_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_read_papers_user_id'))
        batch_op.drop_index(batch_op.f('ix_read_papers_paper_id'))

    op.drop_table('read_papers')
    # ### end Alembic commands ###
