"""empty message

Revision ID: e3bee3e03180
Revises: 0dfbd4ec0131
Create Date: 2025-08-07 20:20:39.955646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bee3e03180'
down_revision: Union[str, Sequence[str], None] = '0dfbd4ec0131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder_papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_paper_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder_papers', schema=None) as batch_op:
        batch_op.drop_column('folder_paper_name')

    # ### end Alembic commands ###
