"""Init

Revision ID: ffcd44760259
Revises: 4f424f6f8541
Create Date: 2025-08-01 16:09:03.982175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcd44760259'
down_revision: Union[str, Sequence[str], None] = '4f424f6f8541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_read_papers_paper_id_papers')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_read_papers_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_papers')),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_user_paper')
    )
    op.create_index(op.f('ix_read_papers_paper_id'), 'read_papers', ['paper_id'], unique=False)
    op.create_index(op.f('ix_read_papers_user_id'), 'read_papers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_read_papers_user_id'), table_name='read_papers')
    op.drop_index(op.f('ix_read_papers_paper_id'), table_name='read_papers')
    op.drop_table('read_papers')
    # ### end Alembic commands ###
