"""empty message

Revision ID: 5efeb22fa03f
Revises: f80082696994
Create Date: 2025-07-11 21:44:59.162452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efeb22fa03f'
down_revision: Union[str, Sequence[str], None] = 'f80082696994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password_chk', sa.String(), nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(length=1024), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    op.drop_column('user', 'password_chk')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
