"""empty message

Revision ID: 7737d8577f6a
Revises: c9765e76381f
Create Date: 2025-07-19 22:16:10.973168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7737d8577f6a'
down_revision: Union[str, Sequence[str], None] = 'c9765e76381f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, Column, Integer, String, MetaData

def upgrade():
    conn = op.get_bind()
    meta = MetaData()
    meta.reflect(bind=conn)  # 여기서 bind 지정

    # 기존 테이블 복사
    old_user = Table("user", meta)

    # 새로운 테이블 정의 (예: phonenumber nullable 변경)
    new_user = Table(
        "user_new", meta,
        Column("id", Integer, primary_key=True),
        Column("username", String, nullable=False),
        Column("email", String, nullable=False),
        Column("phonenumber", String, nullable=True),  # nullable 변경 적용
        # 필요한 다른 컬럼도 모두 포함해야 함
    )

    new_user.create(bind=conn)

    conn.execute(sa.text("""
        INSERT INTO user_new (id, username, email, phonenumber)
        SELECT id, username, email, phonenumber FROM user
    """))

    op.drop_table("user")
    op.rename_table("user_new", "user")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'phonenumber',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_folder_paper_id'), table_name='folder_paper')
    op.drop_table('folder_paper')
    op.drop_table('folder')
    op.drop_table('paper')
    # ### end Alembic commands ###
