"""empty message

Revision ID: 787e6bdfdd52
Revises: 7737d8577f6a
Create Date: 2025-07-19 22:19:59.334369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787e6bdfdd52'
down_revision: Union[str, Sequence[str], None] = '7737d8577f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_phonenumber', ['phonenumber'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'modify_date')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
