"""empty message

Revision ID: c9765e76381f
Revises: 5efeb22fa03f
Create Date: 2025-07-11 21:46:44.341604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9765e76381f'
down_revision: Union[str, Sequence[str], None] = '5efeb22fa03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_chk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_chk', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
